//HintName: ProjectFiles.g.cs
// <auto-generated/>
#nullable enable

namespace ProjectFilesGenerator
{
    using ProjectFilesGenerator.Types;

    /// <summary>Provides strongly-typed access to project files marked with CopyToOutputDirectory.</summary>
    static partial class ProjectFiles
    {
        public new static ProjectFile Equals { get; } = new("Equals");

        public static DocsType Docs { get; } = new();
        public new static ToStringType ToString { get; } = new();
    }
}

namespace ProjectFilesGenerator.Types
{
partial class DocsType() : ProjectDirectory("Docs")
{
    public new InfoType Info { get; } = new();
    public partial class InfoType() : ProjectDirectory("Docs/Info")
    {
        public ProjectFile b_txt { get; } = new("Docs/Info/b.txt");
    }

    public new PathType Path { get; } = new();
    public partial class PathType() : ProjectDirectory("Docs/Path")
    {
        public ProjectFile a_txt { get; } = new("Docs/Path/a.txt");
    }

    public SubType Sub { get; } = new();
    public partial class SubType() : ProjectDirectory("Docs/Sub")
    {
        public new PathType Path { get; } = new();
        public partial class PathType() : ProjectDirectory("Docs/Sub/Path")
        {
            public ProjectFile c_txt { get; } = new("Docs/Sub/Path/c.txt");
        }

    }

    public new ProjectFile ToString { get; } = new("Docs/ToString");
}
partial class ToStringType() : ProjectDirectory("ToString")
{
    public ProjectFile d_txt { get; } = new("ToString/d.txt");
}
}
