//HintName: ProjectFiles.g.cs
// <auto-generated/>
#nullable enable

namespace ProjectFilesGenerator
{
    using ProjectFilesGenerator.Types;

    /// <summary>Provides strongly-typed access to project files marked with CopyToOutputDirectory.</summary>
    static partial class ProjectFiles
    {
        public static ProjectFile config_json { get; } = new("config.json");
        public static ProjectFile data_xml { get; } = new("data.xml");
        public static ProjectFile file_txt { get; } = new("file.txt");
        public static ProjectFile readme_md { get; } = new("readme.md");
        public static ProjectFile script_ps1 { get; } = new("script.ps1");
    }
}

namespace ProjectFilesGenerator.Types
{
}
