//HintName: ProjectFiles.g.cs
// <auto-generated/>
#nullable enable

namespace ProjectFilesGenerator
{
    using ProjectFilesGenerator.Types;

    /// <summary>Provides strongly-typed access to project files marked with CopyToOutputDirectory.</summary>
    static partial class ProjectFiles
    {
        public static ProjectFile readme_md { get; } = new("readme.md");

        public static ConfigType Config { get; } = new();
        public static ScriptsType Scripts { get; } = new();
    }
}

namespace ProjectFilesGenerator.Types
{
partial class ConfigType() : ProjectDirectory("Config")
{
    public ProjectFile appsettings_json { get; } = new("Config/appsettings.json");
}
partial class ScriptsType() : ProjectDirectory("Scripts")
{
    public ProjectFile deploy_ps1 { get; } = new("Scripts/deploy.ps1");
}
}
