//HintName: ProjectFiles.g.cs
// <auto-generated/>
#nullable enable

namespace ProjectFilesGenerator
{
    using ProjectFilesGenerator.Types;

    /// <summary>Provides strongly-typed access to project files marked with CopyToOutputDirectory.</summary>
    static partial class ProjectFiles
    {
        public static ProjectFile _editorconfig { get; } = new(".editorconfig");
        public static ProjectFile _env { get; } = new(".env");
        public static ProjectFile _gitignore { get; } = new(".gitignore");
    }
}

namespace ProjectFilesGenerator.Types
{
}
