//HintName: ProjectFiles.g.cs
// <auto-generated/>
#nullable enable

namespace ProjectFilesGenerator
{
    using ProjectFilesGenerator.Types;

    /// <summary>Provides strongly-typed access to project files marked with CopyToOutputDirectory.</summary>
    static partial class ProjectFiles
    {
        public static EmbeddedResource data_json { get; } = new("TestAssembly.data.json");
        public static ProjectFile other_txt { get; } = new("other.txt");
    }
}

namespace ProjectFilesGenerator.Types
{
}
