//HintName: ProjectFiles.g.cs
// <auto-generated/>
#nullable enable

namespace ProjectFilesGenerator
{
    using ProjectFilesGenerator.Types;

    /// <summary>Provides strongly-typed access to project files marked with CopyToOutputDirectory.</summary>
    static partial class ProjectFiles
    {
        public static AssetsType Assets { get; } = new();
    }
}

namespace ProjectFilesGenerator.Types
{
partial class AssetsType() : ProjectDirectory("Assets")
{
    public ProjectFile data_json { get; } = new("Assets/data.json");
    public EmbeddedResource logo_png { get; } = new("TestAssembly.Assets.logo.png");
}
}
