//HintName: ProjectFiles.g.cs
// <auto-generated/>
#nullable enable

namespace ProjectFilesGenerator
{
    using ProjectFilesGenerator.Types;

    /// <summary>Provides strongly-typed access to project files marked with CopyToOutputDirectory.</summary>
    static partial class ProjectFiles
    {
        public static TemplatesType Templates { get; } = new();
    }
}

namespace ProjectFilesGenerator.Types
{
partial class TemplatesType() : ProjectDirectory("Templates")
{
    public InvoiceType Invoice { get; } = new();
    public partial class InvoiceType() : ProjectDirectory("Templates/Invoice")
    {
        public StylesType Styles { get; } = new();
        public partial class StylesType() : ProjectDirectory("Templates/Invoice/Styles")
        {
            public ProjectFile invoice_css { get; } = new("Templates/Invoice/Styles/invoice.css");
        }

        public ProjectFile invoice_html { get; } = new("Templates/Invoice/invoice.html");
    }

    public ReceiptType Receipt { get; } = new();
    public partial class ReceiptType() : ProjectDirectory("Templates/Receipt")
    {
        public ProjectFile receipt_html { get; } = new("Templates/Receipt/receipt.html");
    }

    public ProjectFile email_html { get; } = new("Templates/email.html");
}
}
