//HintName: ProjectFiles.g.cs
// <auto-generated/>
#nullable enable

namespace ProjectFilesGenerator
{
    using ProjectFilesGenerator.Types;

    /// <summary>Provides strongly-typed access to project files marked with CopyToOutputDirectory.</summary>
    static partial class ProjectFiles
    {
        public static TopType Top { get; } = new();
    }
}

namespace ProjectFilesGenerator.Types
{
partial class TopType() : ProjectDirectory("Top")
{
    public ProjectFile valid_txt { get; } = new("Top/valid.txt");
}
}
