//HintName: ProjectFiles.g.cs
// <auto-generated/>
#nullable enable

namespace ProjectFilesGenerator
{
    using ProjectFilesGenerator.Types;

    /// <summary>Provides strongly-typed access to project files marked with CopyToOutputDirectory.</summary>
    static partial class ProjectFiles
    {
        public static ProjectFile also_has_metadata_txt { get; } = new("also-has-metadata.txt");
        public static ProjectFile has_metadata_json { get; } = new("has-metadata.json");
    }
}

namespace ProjectFilesGenerator.Types
{
}
