//HintName: ProjectFiles.g.cs
// <auto-generated/>
#nullable enable

namespace ProjectFilesGenerator
{
    using ProjectFilesGenerator.Types;

    /// <summary>Provides strongly-typed access to project files marked with CopyToOutputDirectory.</summary>
    static partial class ProjectFiles
    {
        public static ProjectFile appsettings_Development_json { get; } = new("appsettings.Development.json");
        public static ProjectFile appsettings_Production_json { get; } = new("appsettings.Production.json");
        public static ProjectFile appsettings_json { get; } = new("appsettings.json");
    }
}

namespace ProjectFilesGenerator.Types
{
}
