//HintName: ProjectFiles.g.cs
// <auto-generated/>
#nullable enable

namespace ProjectFilesGenerator
{
    using ProjectFilesGenerator.Types;

    /// <summary>Provides strongly-typed access to project files marked with CopyToOutputDirectory.</summary>
    static partial class ProjectFiles
    {
        public static ProjectFile file_in_other_project_txt { get; } = new("file in other project.txt");
    }
}

namespace ProjectFilesGenerator.Types
{
}
