//HintName: ProjectFiles.g.cs
// <auto-generated/>
#nullable enable

namespace ProjectFilesGenerator
{
    using ProjectFilesGenerator.Types;

    /// <summary>Provides strongly-typed access to project files marked with CopyToOutputDirectory.</summary>
    static partial class ProjectFiles
    {
        public static AssetsType Assets { get; } = new();
    }
}

namespace ProjectFilesGenerator.Types
{
partial class AssetsType() : ProjectDirectory("Assets")
{
    public ImagesType Images { get; } = new();
    public partial class ImagesType() : ProjectDirectory("Assets/Images")
    {
        public ProjectFile logo_png { get; } = new("Assets/Images/logo.png");
    }

    public ScriptsType Scripts { get; } = new();
    public partial class ScriptsType() : ProjectDirectory("Assets/Scripts")
    {
        public ProjectFile app_js { get; } = new("Assets/Scripts/app.js");
    }

    public StylesType Styles { get; } = new();
    public partial class StylesType() : ProjectDirectory("Assets/Styles")
    {
        public ProjectFile theme_css { get; } = new("Assets/Styles/theme.css");
    }

}
}
