//HintName: ProjectFiles.g.cs
// <auto-generated/>
#nullable enable

namespace ProjectFilesGenerator
{
    using ProjectFilesGenerator.Types;

    /// <summary>Provides strongly-typed access to project files marked with CopyToOutputDirectory.</summary>
    static partial class ProjectFiles
    {
        public static Dir1Type Dir1 { get; } = new();
        public static Dir2Type Dir2 { get; } = new();
    }
}

namespace ProjectFilesGenerator.Types
{
partial class Dir1Type() : ProjectDirectory("Dir1")
{
    public ProjectFile config_json { get; } = new("Dir1/config.json");
}
partial class Dir2Type() : ProjectDirectory("Dir2")
{
    public ProjectFile config_json { get; } = new("Dir2/config.json");
}
}
