//HintName: ProjectFiles.g.cs
// <auto-generated/>
#nullable enable

namespace ProjectFilesGenerator
{
    using ProjectFilesGenerator.Types;

    /// <summary>Provides strongly-typed access to project files marked with CopyToOutputDirectory.</summary>
    static partial class ProjectFiles
    {
        public static ProjectFile readme_md { get; } = new("readme.md");

        public static ConfigType Config { get; } = new();
        public static ResourcesType Resources { get; } = new();
    }
}

namespace ProjectFilesGenerator.Types
{
partial class ConfigType() : ProjectDirectory("Config")
{
    public ProjectFile appsettings_json { get; } = new("Config/appsettings.json");
}
partial class ResourcesType() : ProjectDirectory("Resources")
{
    public EmbeddedResource logo_png { get; } = new("TestAssembly.Resources.logo.png");
}
}
