//HintName: ProjectFiles.g.cs
// <auto-generated/>
#nullable enable

namespace ProjectFilesGenerator
{
    using ProjectFilesGenerator.Types;

    /// <summary>Provides strongly-typed access to project files marked with CopyToOutputDirectory.</summary>
    static partial class ProjectFiles
    {
        public static ProjectDirectory SolutionDirectory { get; } = new("C:/Work/");
        public static ProjectFile SolutionFile { get; } = new("C:/Work/Library.sln");

        public static ProjectFile readme_md { get; } = new("readme.md");
    }
}

namespace ProjectFilesGenerator.Types
{
}
