//HintName: ProjectFiles.g.cs
// <auto-generated/>
#nullable enable

namespace ProjectFilesGenerator
{
    using ProjectFilesGenerator.Types;

    /// <summary>Provides strongly-typed access to project files marked with CopyToOutputDirectory.</summary>
    static partial class ProjectFiles
    {
        public static ProjectDirectory ProjectDirectory { get; } = new("C:/Code/C#/My;App/");
        public static ProjectFile ProjectFile { get; } = new("C:/Code/C#/My;App/MyApp.csproj");
        public static ProjectDirectory SolutionDirectory { get; } = new("C:/Code/C#/");
        public static ProjectFile SolutionFile { get; } = new("C:/Code/C#/MySolution.sln");

        public static ProjectFile a_b_txt { get; } = new("a;b.txt");

        public static DocsType Docs { get; } = new();
        public static ResourcesType Resources { get; } = new();
    }
}

namespace ProjectFilesGenerator.Types
{
partial class DocsType() : ProjectDirectory("Docs")
{
    public C_Type C_ { get; } = new();
    public partial class C_Type() : ProjectDirectory("Docs/C#")
    {
        public ProjectFile note_txt { get; } = new("Docs/C#/note.txt");
    }

}
partial class ResourcesType() : ProjectDirectory("Resources")
{
    public C_Type C_ { get; } = new();
    public partial class C_Type() : ProjectDirectory("Resources/C#")
    {
        public EmbeddedResource logo_png { get; } = new("My#App.Resources.logo.png");
    }

}
}
