//HintName: ProjectFiles.g.cs
// <auto-generated/>
#nullable enable

namespace ProjectFilesGenerator
{
    using ProjectFilesGenerator.Types;

    /// <summary>Provides strongly-typed access to project files marked with CopyToOutputDirectory.</summary>
    static partial class ProjectFiles
    {
        public static RootType Root { get; } = new();
    }
}

namespace ProjectFilesGenerator.Types
{
partial class RootType() : ProjectDirectory("Root")
{
    public Level1Type Level1 { get; } = new();
    public partial class Level1Type() : ProjectDirectory("Root/Level1")
    {
        public Level2Type Level2 { get; } = new();
        public partial class Level2Type() : ProjectDirectory("Root/Level1/Level2")
        {
            public Level3Type Level3 { get; } = new();
            public partial class Level3Type() : ProjectDirectory("Root/Level1/Level2/Level3")
            {
                public ProjectFile deep_txt { get; } = new("Root/Level1/Level2/Level3/deep.txt");
            }

        }

        public ProjectFile file1_txt { get; } = new("Root/Level1/file1.txt");
    }

    public ProjectFile file2_txt { get; } = new("Root/file2.txt");
}
}
