//HintName: ProjectFiles.g.cs
// <auto-generated/>
#nullable enable

namespace ProjectFilesGenerator
{
    using ProjectFilesGenerator.Types;

    /// <summary>Provides strongly-typed access to project files marked with CopyToOutputDirectory.</summary>
    static partial class ProjectFiles
    {
        public static ProjectFile app_settings_dev_json { get; } = new("app.settings.dev.json");
        public static ProjectFile file_with_underscore_txt { get; } = new("file_with_underscore.txt");
        public static ProjectFile my_config_json { get; } = new("my-config.json");
    }
}

namespace ProjectFilesGenerator.Types
{
}
