//HintName: ProjectFiles.g.cs
// <auto-generated/>
#nullable enable

namespace ProjectFilesGenerator
{
    using ProjectFilesGenerator.Types;

    /// <summary>Provides strongly-typed access to project files marked with CopyToOutputDirectory.</summary>
    static partial class ProjectFiles
    {
        public static ResourcesType Resources { get; } = new();
    }
}

namespace ProjectFilesGenerator.Types
{
partial class ResourcesType() : ProjectDirectory("Resources")
{
    public EmbeddedResource logo_png { get; } = new("TestAssembly.Resources.logo.png");
    public EmbeddedResource template_txt { get; } = new("TestAssembly.Resources.template.txt");
}
}
