//HintName: ProjectFiles.g.cs
// <auto-generated/>
#nullable enable

namespace ProjectFilesGenerator
{
    using ProjectFilesGenerator.Types;

    /// <summary>Provides strongly-typed access to project files marked with CopyToOutputDirectory.</summary>
    static partial class ProjectFiles
    {
        public static ProjectFile ProjectFile_json { get; } = new("ProjectFile.json");
        public static ProjectFile SolutionFile_xml { get; } = new("SolutionFile.xml");

        public static SolutionFile_BackupType SolutionFile_Backup { get; } = new();
    }
}

namespace ProjectFilesGenerator.Types
{
partial class SolutionFile_BackupType() : ProjectDirectory("SolutionFile.Backup")
{
    public ProjectFile a_txt { get; } = new("SolutionFile.Backup/a.txt");
}
}
