//HintName: ProjectFiles.g.cs
// <auto-generated/>
#nullable enable

namespace ProjectFilesGenerator
{
    using ProjectFilesGenerator.Types;

    /// <summary>Provides strongly-typed access to project files marked with CopyToOutputDirectory.</summary>
    static partial class ProjectFiles
    {
        public static ConfigType Config { get; } = new();
    }
}

namespace ProjectFilesGenerator.Types
{
partial class ConfigType() : ProjectDirectory("Config")
{
    public ProjectFile appsettings_json { get; } = new("Config/appsettings.json");
    public ProjectFile database_json { get; } = new("Config/database.json");
}
}
