//HintName: ProjectFiles.g.cs
// <auto-generated/>
#nullable enable

namespace ProjectFilesGenerator
{
    using ProjectFilesGenerator.Types;

    /// <summary>Provides strongly-typed access to project files marked with CopyToOutputDirectory.</summary>
    static partial class ProjectFiles
    {
        public static ResourcesType Resources { get; } = new();
    }
}

namespace ProjectFilesGenerator.Types
{
partial class ResourcesType() : ProjectDirectory("Resources")
{
    public ImagesType Images { get; } = new();
    public partial class ImagesType
    {
        public IconsType Icons { get; } = new();
        public partial class IconsType
        {
            public EmbeddedResource home_svg { get; } = new("TestAssembly.Resources.Images.Icons.home.svg");
        }

    }

    public EmbeddedResource strings_json { get; } = new("TestAssembly.Resources.strings.json");
}
}
