//HintName: GeneratedPaths.g.cs
// <auto-generated/>
#nullable enable

/// <summary>
/// Represents a path segment that can be composed using the / operator.
/// </summary>
public readonly struct PathNode
{
    /// <summary>
    /// Gets the path value.
    /// </summary>
    public string Value { get; }

    /// <summary>
    /// Initializes a new instance of the <see cref="PathNode"/> struct.
    /// </summary>
    /// <param name="value">The path value.</param>
    public PathNode(string value) => Value = value;

    /// <summary>
    /// Returns the string representation of this path node.
    /// </summary>
    public override string ToString() => Value;

    /// <summary>
    /// Implicitly converts a <see cref="PathNode"/> to a string.
    /// </summary>
    public static implicit operator string(PathNode p) => p.Value;

    /// <summary>
    /// Gets an empty path node.
    /// </summary>
    public static PathNode Empty => new PathNode("");

    /// <summary>
    /// Combines two path nodes using the / separator.
    /// </summary>
    public static PathNode operator /(PathNode left, PathNode right)
        => new PathNode(string.IsNullOrEmpty(left.Value) ? right.Value : left.Value + "/" + right.Value);

    /// <summary>
    /// Combines a path node with a string using the / separator.
    /// </summary>
    public static PathNode operator /(PathNode left, string right)
        => new PathNode(string.IsNullOrEmpty(left.Value) ? right : left.Value + "/" + right);
}

/// <summary>
/// Provides path composition support using the / operator for project files.
/// Use with 'using static GeneratedPaths;' to access directory and file path nodes.
/// </summary>
public static class GeneratedPaths
{
    /// <summary>
    /// File extensions for 'config'.
    /// </summary>
    public static class Config
    {
        /// <summary>
        /// PathNode for 'config.json'.
        /// </summary>
        public static PathNode Json => new PathNode("config.json");

    }

    /// <summary>
    /// File extensions for 'data'.
    /// </summary>
    public static class Data
    {
        /// <summary>
        /// PathNode for 'data.csv'.
        /// </summary>
        public static PathNode Csv => new PathNode("data.csv");

    }

}
