//HintName: ProjectFiles.g.cs
// <auto-generated/>
#nullable enable

/// <summary>
/// Provides strongly-typed access to project files marked with CopyToOutputDirectory.
/// </summary>
public static partial class ProjectFiles
{
    /// <summary>
    /// Files in the 'Configs' directory.
    /// </summary>
    public static partial class Configs
    {
        public static string AppsettingsJson => "Configs\\appsettings.json";

        public static string DatabaseJson => "Configs\\database.json";

        public static string LoggingJson => "Configs\\logging.json";

    }

}
