//HintName: ProjectFiles.g.cs
// <auto-generated/>
#nullable enable

/// <summary>
/// Provides strongly-typed access to project files marked with CopyToOutputDirectory.
/// </summary>
public static partial class ProjectFiles
{
    /// <summary>
    /// Files in the 'Config' directory.
    /// </summary>
    public static partial class Config
    {
        public static string Appsettings_json => "Config\\appsettings.json";

    }

    /// <summary>
    /// Files in the 'Data' directory.
    /// </summary>
    public static partial class Data
    {
        public static string Users_csv => "Data\\users.csv";

    }

    /// <summary>
    /// Files in the 'wwwroot' directory.
    /// </summary>
    public static partial class Wwwroot
    {
        public static string Index_html => "wwwroot\\index.html";

    }

}
