//HintName: ProjectFiles.g.cs
// <auto-generated/>
#nullable enable

/// <summary>
/// Provides strongly-typed access to project files marked with CopyToOutputDirectory.
/// </summary>
public static partial class ProjectFiles
{
    public static string @classTxt => "class.txt";

    public static string @namespaceJson => "namespace.json";

    public static string @staticXml => "static.xml";

}
