//HintName: ProjectFiles.g.cs
// <auto-generated/>
#nullable enable

/// <summary>
/// Provides strongly-typed access to project files marked with CopyToOutputDirectory.
/// </summary>
public static partial class ProjectFiles
{
    /// <summary>
    /// Files in the 'Assets' directory.
    /// </summary>
    public static partial class Assets
    {
        public static string File1_txt => "Assets\\file1.txt";

        /// <summary>
        /// Files in the 'SubDir' directory.
        /// </summary>
        public static partial class SubDir
        {
            public static string File2_json => "Assets\\SubDir\\file2.json";

            /// <summary>
            /// Files in the 'Nested' directory.
            /// </summary>
            public static partial class Nested
            {
                public static string File3_xml => "Assets\\SubDir\\Nested\\file3.xml";

            }

        }

    }

}
