//HintName: ProjectFiles.g.cs
// <auto-generated/>
#nullable enable

using ProjectFilesGenerator.Types;

namespace ProjectFilesGenerator
{
    /// <summary>Provides strongly-typed access to project files marked with CopyToOutputDirectory.</summary>
    public static partial class ProjectFiles
    {
        public static AssetsType Assets { get; } = new();
    }
}

namespace ProjectFilesGenerator.Types
{
public partial class AssetsType
{
    public DataType Data { get; } = new();
    public partial class DataType
    {
        public string users_csv => "Assets\\Data\\users.csv";
    }

    public ImagesType Images { get; } = new();
    public partial class ImagesType
    {
        public string logo_png => "Assets\\Images\\logo.png";
    }

}
}
