//HintName: ProjectFiles.g.cs
// <auto-generated/>
#nullable enable

/// <summary>
/// Provides strongly-typed access to project files marked with CopyToOutputDirectory.
/// </summary>
public static partial class ProjectFiles
{
    /// <summary>
    /// Files in the 'Assets' directory.
    /// </summary>
    public static partial class Assets
    {
        /// <summary>
        /// Files in the 'Data' directory.
        /// </summary>
        public static partial class Data
        {
            /// <summary>
            /// Files in the 'Config' directory.
            /// </summary>
            public static partial class Config
            {
                public static string Secrets_json => "Assets\\Data\\Config\\secrets.json";

                public static string Settings_json => "Assets\\Data\\Config\\settings.json";

            }

            /// <summary>
            /// Files in the 'Seeds' directory.
            /// </summary>
            public static partial class Seeds
            {
                public static string Users_csv => "Assets\\Data\\Seeds\\users.csv";

            }

        }

        /// <summary>
        /// Files in the 'Fonts' directory.
        /// </summary>
        public static partial class Fonts
        {
            public static string Roboto_ttf => "Assets\\Fonts\\roboto.ttf";

        }

        /// <summary>
        /// Files in the 'Images' directory.
        /// </summary>
        public static partial class Images
        {
            /// <summary>
            /// Files in the 'Backgrounds' directory.
            /// </summary>
            public static partial class Backgrounds
            {
                public static string Header_jpg => "Assets\\Images\\Backgrounds\\header.jpg";

            }

            /// <summary>
            /// Files in the 'Icons' directory.
            /// </summary>
            public static partial class Icons
            {
                public static string Favicon_ico => "Assets\\Images\\Icons\\favicon.ico";

                public static string Logo_png => "Assets\\Images\\Icons\\logo.png";

            }

        }

        public static string Readme_txt => "Assets\\readme.txt";

    }

}
