//HintName: ProjectFiles.g.cs
// <auto-generated/>
#nullable enable

using ProjectFilesGenerator.Types;

namespace ProjectFilesGenerator
{
    /// <summary>Provides strongly-typed access to project files marked with CopyToOutputDirectory.</summary>
    public static partial class ProjectFiles
    {
        public static ConfigType Config { get; } = new();
        public static DataType Data { get; } = new();
        public static wwwrootType wwwroot { get; } = new();
    }
}

namespace ProjectFilesGenerator.Types
{
public partial class ConfigType
{
    public string appsettings_json => "Config\\appsettings.json";
}
public partial class DataType
{
    public string users_csv => "Data\\users.csv";
}
public partial class wwwrootType
{
    public string index_html => "wwwroot\\index.html";
}
}
