//HintName: ProjectFiles.g.cs
// <auto-generated/>
#nullable enable

/// <summary>
/// Provides strongly-typed access to project files marked with CopyToOutputDirectory.
/// </summary>
public static partial class ProjectFiles
{
    public static string FileWithDots_txt => "file.with.dots.txt";

    public static string MyConfig_json => "my-config.json";

    public static string User_data_csv => "user_data.csv";

}
