//HintName: ProjectFiles.g.cs
// <auto-generated/>
#nullable enable

using ProjectFilesGenerator.Types;

namespace ProjectFilesGenerator
{
    /// <summary>Provides strongly-typed access to project files marked with CopyToOutputDirectory.</summary>
    public static partial class ProjectFiles
    {
        public static ConfigsType Configs { get; } = new();
    }
}

namespace ProjectFilesGenerator.Types
{
public partial class ConfigsType
{
    public string appsettings_json => "Configs\\appsettings.json";
    public string database_json => "Configs\\database.json";
    public string logging_json => "Configs\\logging.json";
}
}
