//HintName: ProjectFiles.g.cs
// <auto-generated/>
#nullable enable

/// <summary>
/// Provides strongly-typed access to project files marked with CopyToOutputDirectory.
/// </summary>
public static partial class ProjectFiles
{
    public static string @class_txt => "class.txt";

    public static string @namespace_json => "namespace.json";

    public static string @static_xml => "static.xml";

}
