//HintName: ProjectFiles.g.cs
// <auto-generated/>
#nullable enable

/// <summary>
/// Provides strongly-typed access to project files marked with CopyToOutputDirectory.
/// </summary>
public static partial class ProjectFiles
{
    public static string FileWithDotsTxt => "file.with.dots.txt";

    public static string MyConfigJson => "my-config.json";

    public static string User_dataCsv => "user_data.csv";

}
