//HintName: ProjectFiles.g.cs
// <auto-generated/>
#nullable enable

using ProjectFilesGenerator.Types;

namespace ProjectFilesGenerator
{
    /// <summary>Provides strongly-typed access to project files marked with CopyToOutputDirectory.</summary>
    public static partial class ProjectFiles
    {
        public static Assets Assets { get; } = new();
    }
}

namespace ProjectFilesGenerator.Types
{
public partial class Assets
{
    public SubDirType SubDir { get; } = new();
    public partial class SubDirType
    {
        public NestedType Nested { get; } = new();
        public partial class NestedType
        {
            public string file3_xml => "Assets\\SubDir\\Nested\\file3.xml";
        }

        public string file2_json => "Assets\\SubDir\\file2.json";
    }

    public string file1_txt => "Assets\\file1.txt";
}
}
