//HintName: ProjectFiles.g.cs
// <auto-generated/>
#nullable enable

/// <summary>
/// Provides strongly-typed access to project files marked with CopyToOutputDirectory.
/// </summary>
public static partial class ProjectFiles
{
    public static string _1FirstTxt => "1-first.txt";

    public static string File123Json => "file123.json";

}
