//HintName: ProjectFiles.g.cs
// <auto-generated/>
#nullable enable

using ProjectFilesGenerator.Types;

namespace ProjectFilesGenerator
{
    /// <summary>Provides strongly-typed access to project files marked with CopyToOutputDirectory.</summary>
    public static partial class ProjectFiles
    {
        public static Assets Assets { get; } = new();
    }
}

namespace ProjectFilesGenerator.Types
{
public partial class Assets
{
    public DataType Data { get; } = new();
    public partial class DataType
    {
        public ConfigType Config { get; } = new();
        public partial class ConfigType
        {
            public string Secrets_json => "Assets\\Data\\Config\\secrets.json";
            public string Settings_json => "Assets\\Data\\Config\\settings.json";
        }

        public SeedsType Seeds { get; } = new();
        public partial class SeedsType
        {
            public string Users_csv => "Assets\\Data\\Seeds\\users.csv";
        }

    }

    public FontsType Fonts { get; } = new();
    public partial class FontsType
    {
        public string Roboto_ttf => "Assets\\Fonts\\roboto.ttf";
    }

    public ImagesType Images { get; } = new();
    public partial class ImagesType
    {
        public BackgroundsType Backgrounds { get; } = new();
        public partial class BackgroundsType
        {
            public string Header_jpg => "Assets\\Images\\Backgrounds\\header.jpg";
        }

        public IconsType Icons { get; } = new();
        public partial class IconsType
        {
            public string Favicon_ico => "Assets\\Images\\Icons\\favicon.ico";
            public string Logo_png => "Assets\\Images\\Icons\\logo.png";
        }

    }

    public string Readme_txt => "Assets\\readme.txt";
}
}
