//HintName: ProjectFiles.g.cs
// <auto-generated/>
#nullable enable

/// <summary>
/// Provides strongly-typed access to project files marked with CopyToOutputDirectory.
/// </summary>
public static partial class ProjectFiles
{
    /// <summary>
    /// Files in the 'Assets' directory.
    /// </summary>
    public static partial class Assets
    {
        /// <summary>
        /// Files in the 'Data' directory.
        /// </summary>
        public static partial class Data
        {
            public static string UsersCsv => "Assets\\Data\\users.csv";

        }

        /// <summary>
        /// Files in the 'Images' directory.
        /// </summary>
        public static partial class Images
        {
            public static string LogoPng => "Assets\\Images\\logo.png";

        }

    }

}
