//HintName: ProjectFiles.g.cs
// <auto-generated/>
#nullable enable

using ProjectFilesGenerator.Types;

namespace ProjectFilesGenerator
{
    /// <summary>
    /// Provides strongly-typed access to project files marked with CopyToOutputDirectory.
    /// </summary>
    public static partial class ProjectFiles
    {
    }
}

namespace ProjectFilesGenerator.Types
{
}
